# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(393, 46)
        Form.setMinimumSize(QtCore.QSize(393, 46))
        Form.setMaximumSize(QtCore.QSize(393, 46))
        self.selectAreaPushButton = QtWidgets.QPushButton(Form)
        self.selectAreaPushButton.setGeometry(QtCore.QRect(10, 10, 101, 24))
        self.selectAreaPushButton.setObjectName("selectAreaPushButton")
        self.startCapturePushButton = QtWidgets.QPushButton(Form)
        self.startCapturePushButton.setGeometry(QtCore.QRect(120, 10, 101, 24))
        self.startCapturePushButton.setObjectName("startCapturePushButton")
        self.createDocumentPushButton = QtWidgets.QPushButton(Form)
        self.createDocumentPushButton.setGeometry(
            QtCore.QRect(240, 10, 141, 24))
        self.createDocumentPushButton.setObjectName("createDocumentPushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "StepCapture"))
        self.selectAreaPushButton.setText(_translate("Form", "Select Area"))
        self.startCapturePushButton.setText(
            _translate("Form", "Start Capture"))
        self.createDocumentPushButton.setText(
            _translate("Form", "Create Document"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
